#!/usr/bin/env node

/**
 * Environment Variable Injection Script
 * 
 * This script solves the problem of making Node.js environment variables available
 * in the browser bundle at runtime. Since process.env is not available in the browser,
 * we generate a temporary TypeScript file with the actual values at build time.
 * 
 * How it works:
 * 1. Reads environment variables from process.env
 * 2. Generates src/environments/environment.prod.generated.ts with actual values
 * 3. Angular's fileReplacements in production config swaps this file in
 * 4. The generated file is gitignored to prevent credential leaks
 * 
 * Usage:
 *   export NG_FIREBASE_API_KEY=xxx
 *   node scripts/inject-env.js
 *   ng build --configuration production
 * 
 * Or use the npm script:
 *   npm run build:prod
 */

const fs = require('fs');
const path = require('path');

// Check if running in strict mode (CI should use this)
const strictMode = process.argv.includes('--strict') || process.env.CI === 'true';

// Environment variables to inject
const envVars = [
  'NG_FIREBASE_API_KEY',
  'NG_FIREBASE_AUTH_DOMAIN',
  'NG_FIREBASE_MESSAGING_SENDER_ID',
  'NG_FIREBASE_APP_ID',
];

try {
  // Collect environment variable values
  const envValues = {};
  const missingVars = [];

  envVars.forEach((varName) => {
    const value = process.env[varName];
    if (!value) {
      missingVars.push(varName);
    }
    envValues[varName] = value || '';
  });

  // In strict mode (CI), fail hard on missing variables
  if (missingVars.length > 0) {
    console.error('❌ Error: The following required environment variables are not set:');
    missingVars.forEach((varName) => console.error(`   - ${varName}`));
    
    if (strictMode) {
      console.error('\n   Running in strict mode (CI or --strict flag).');
      console.error('   Build cannot proceed without all required environment variables.');
      process.exit(1);
    } else {
      console.warn('\n⚠️  Warning: These will be set to empty strings in the build.');
      console.warn('   The application may not function correctly without proper credentials.');
      console.warn('   Use --strict flag or set CI=true to fail on missing variables.');
    }
  }

  // Generate the TypeScript file content
  const outputPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.generated.ts');
  
  // Ensure the directory exists
  const outputDir = path.dirname(outputPath);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }
  
  const fileContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by scripts/inject-env.js at build time
 * This file contains actual environment variable values and is gitignored
 */

export const environment = {
  production: true,
  firebase: {
    apiKey: ${JSON.stringify(envValues.NG_FIREBASE_API_KEY)},
    authDomain: ${JSON.stringify(envValues.NG_FIREBASE_AUTH_DOMAIN)},
    projectId: 'ecclespark-info',
    storageBucket: 'ecclespark-info.firebasestorage.app',
    messagingSenderId: ${JSON.stringify(envValues.NG_FIREBASE_MESSAGING_SENDER_ID)},
    appId: ${JSON.stringify(envValues.NG_FIREBASE_APP_ID)},
  },
};
`;

  // Write the generated file
  fs.writeFileSync(outputPath, fileContent);
  
  console.log('✓ Generated environment.prod.generated.ts with injected values');
  if (missingVars.length === 0) {
    console.log('✓ All required environment variables are present');
  }

} catch (error) {
  console.error('❌ Failed to generate environment file:');
  
  if (error.code === 'ENOENT') {
    console.error('   File or directory not found.');
    console.error('   Ensure you are running this script from the project root.');
  } else if (error.code === 'EACCES') {
    console.error('   Permission denied writing to src/environments/');
  } else {
    console.error(`   ${error.message}`);
  }
  
  console.error('\nStack trace:');
  console.error(error.stack);
  process.exit(1);
}
