name: Hugo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Set up node and copy files
        run: yarn

      - name: Build and Publish Site
        uses: chabad360/hugo-gh-pages@master
        with:
          githubToken: ${{ secrets.BUILD_TOKEN }}
          args: --gc --minify --cleanDestinationDir --baseURL="https://jloosli.github.io/ecclespark-info/"

      - name: Send Push Notification
        uses: techulus/push-github-action@1.0.0
        env:
          API_KEY: ${{ secrets.PUSH_KEY }}
          MESSAGE: "ecclespark.info build completed"
          TITLE: "Build Success"
          LINK: https://ecclespark.info
